- hosts: node*
  become: yes
  vars:
    bazel_version: 0.18.0
  tasks:
    - apt: name={{ item }}
      loop:
        - openjdk-8-jdk
        - unzip
    - get_url:
        url: "https://github.com/bazelbuild/bazel/releases/download/{{ bazel_version }}/bazel-{{ bazel_version }}-installer-linux-x86_64.sh"
        dest: "/opt/bazel-{{ bazel_version }}-installer-linux-x86_64.sh"
    - shell: "bash /opt/bazel-{{ bazel_version }}-installer-linux-x86_64.sh"

- hosts: cache
  become: yes
  tasks:
    - apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
    - apt_repository: repo="deb https://download.docker.com/linux/ubuntu bionic stable" update_cache=yes
    - apt: name={{ item }}
      loop:
        - docker-ce
        - python-pip
    - pip: name=docker-py
    - service: name=docker state=started enabled=yes

    - file: name=/data state=directory
    - docker_container:
        name: bazel_cache
        image: "buchgr/bazel-remote-cache"
        volumes:
          - "/data:/data"
        ports:
          - 8080:8080